import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';

const kBottomNavIconSize = 20.0;
const kLoaderWidth = 250.0;
const kLoaderHeight = 250.0;
const kLoginLogoSize = 150.0;
const kLoginButtonBottomMargin = EdgeInsets.only(bottom: 10);
const kLoginButtonPadding = EdgeInsets.all(30);
const kLoginButtonIconColor = Colors.white;
const kAppBarUserIcon = Icon(FontAwesomeIcons.userCircle, color:Colors.pink);
const kGridPadding = EdgeInsets.all(20.0);
const kGridCrossAxisSpace = 10.0;
const kGridCrossAxisCount = 2;
const kTopicItemPadding = EdgeInsets.only(left: 10, right: 10);
const kTopicItemTextStyle = TextStyle(height: 1.5, fontWeight: FontWeight.bold);
const kTopicItemOverflow = TextOverflow.fade;
const kTopicItemSoftWrap = false;
const kTopicDetailTitleStyle = TextStyle(height: 2, fontSize: 20, fontWeight: FontWeight.bold);
const kQuizCardShape = RoundedRectangleBorder(borderRadius: BorderRadius.zero);
const kQuizCardMargin = EdgeInsets.all(4);
const kQuizCardElevation = 4.0;
const kQuizCardPadding = EdgeInsets.all(8);
const kQuizCardOverflow = TextOverflow.fade;